### PR TITLE
Update theme

### PR DESCRIPTION
**Pull request by sharkmoos**
I have removed the dependency on @jackorcherton [HackIt theme](https://github.com/jackorcherton/HackIt). Cov-ComSec now runs it's own fork of the HackIt theme, currently with only minor changes. I have also switched from using a remote theme to a local one, and setup the local theme as a submodule of `Cov-ComSec/HackIt`

Default TOC behaviour on a page is the same as before, however:

- TOC can now be disabled via a page's font matter with the following line `toc: false`
- A TOC can be added to a page in a custom location using the shortcode `{{< toc >}}`. 
- An example of the above can be found in the DownUnderCTF page

At the moment, the writing is blue not grey which is annoying but not a deal breaker. I guess the base page is marking the text as a link so making it blue. Will require more SCSS-Fu to prevent that.

### CODE REVIEW

**Comment by sharkmoos** [comment]
If approved, please do not merge. This could be a breaking merge, depending on if the default Hugo build action clones submodules. I will merge to monitor for issues

**Comment by jackorcherton** [comment]
Yes please don't break my site 🤣

Also, @sharkmoos  did you realise it was already possible to disable the contents of a blog post in the front matter with:

```yaml
toc:
  enable: true
  auto: true
```

(Changing to false as needed)

If memory serves, then the action *should* handle submodules as this was how it was originally setup, however, may need to change something in the site config .

Also, I'm more than happy to accept PR's upstream

**Comment by sharkmoos** [comment]
Uhh I know you can do that in the toml file [here](https://github.com/Cov-ComSec/Cov-ComSec.github.io/blob/main/config.toml#L145-L148), and I know you can override it in a page's font matter, this seems more concise and I wasn't sure what other behaviour it would trigger (eg whether it doesn't create a page index at all).

**Comment by jackorcherton** [comment]
I'd have to test it to know

**Comment by sharkmoos** [comment]
Feel free to. I dont mind leaving this open for a few days.

**Review by aukagen — COMMENTED** [review]
Seems good to me. The blue text isn’t a problem but could it be fixed in the future?

**Review by aukagen — APPROVED** [review]

**Comment by jackorcherton** [comment]
@sharkmoos , as far as I can see, it does not impact indexing (as it is still listed under blog posts)

**Comment by jackorcherton** [comment]
This is the comments from the original theme I based mine on:

```yaml
toc:
      # whether to enable the table of the contents
      enable = true
      # whether to make the table of the contents in the sidebar automatically collapsed
      auto = true
```

**Pull request merged**
